accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup

urlpatterns = [
    path("signup/", signup, name="signup"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
]

projects/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView, ProjectCreateView

urlpatterns = [
    path("create/", ProjectCreateView.as_view(), name="create_project"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("", ProjectListView.as_view(), name="list_projects"),
]

tasks/urls.py
from django.urls import path
from .views import TaskCreateView, TaskListView, TaskUpdateView

urlpatterns = [
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("tasks/", include("tasks.urls")),
    path("accounts/", include("accounts.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("projects/", include("projects.urls")),
    path("admin/", admin.site.urls),
]

projects/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField("auth.User", related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        "auth.User", related_name="tasks", null=True, on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

projects/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from projects.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.assignee = self.request.user
        item.save()
        return redirect("show_project", pk=item.id)

tasks/views.py
from django.shortcuts import redirect
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from tasks.models import Task
from django.views.generic.list import ListView
from django.urls import reverse_lazy

# Create your views here.


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.assignee = self.request.user
        item.save()
        return redirect("show_project", pk=item.id)


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "tasks/list.html"
    fields = ["is_completed"]
    success_url = reverse_lazy("show_my_tasks")

projects/templates/base.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>

    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'show_my_tasks' %}">My tasks</a></li>
                        <li><a href="{% url 'list_projects' %}">My projects</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            {% block main %}
            {% endblock main %}
        </main>

    </body>

</html>

projects/templates/projects/create.html
{% extends 'base.html' %}
{% block main %}
    <div>
        <h1>Create a new project</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
{% endblock main %}

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% block main %}
    <div>
        <h1>{{ project.name }}</h1>
        {{ project.description|markdownify }}
        <h2>Tasks</h2>
        <p><a href="{% url 'create_task' %}">Create a new task</a></p>
        {% if project.tasks.all|length > 0 %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Is completed</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tasks in project.tasks.all %}
                        <tr>
                            <td>{{ tasks.name }}</td>
                            <td>{{ tasks.assignee }}</td>
                            <td>{{ tasks.start_date }}</td>
                            <td>{{ tasks.due_date }}</td>
                            {% if tasks.is_completed == True %}
                                <td>yes</td>
                            {% else %}
                                <td>no</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>This project has no tasks</p>
        {% endif %}
    </div>
{% endblock main %}

projects/templates/projects/list.html
{% extends 'base.html' %}
{% block main %}
    <div>
        <h1>My Projects</h1>
        <a href="{% url 'create_project' %}">Create a new project</a>
        {% if not project_list %}
            <p>You are not assigned to any projects</p>
        {% else %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of tasks</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in project_list %}
                        <tr>
                            <td><a href="{% url 'show_project' project.pk %}"> {{ project.name }}</a></td>
                            <td>{{ project.tasks.all|length }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

        {% endif %}
    </div>
{% endblock main %}

tasks/templates/tasks/create.html
{% extends 'base.html' %}
{% block main %}
    <div>
        <h1>Create a new task</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button>Create</button>
        </form>
    </div>
{% endblock main %}

tasks/templates/tasks/list.html
{% extends 'base.html' %}
{% block main %}
    <div>
        <h1>My Tasks</h1>
        {% if task_list|length > 0 %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Start date</th>
                        <th>End date</th>
                        <th>Is completed</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tasks in task_list %}
                        <tr>
                            <td>{{ tasks.name }}</td>
                            <td>{{ tasks.start_date }}</td>
                            <td>{{ tasks.due_date }}</td>
                            {% if tasks.is_completed == True %}
                                <td>Done</td>
                            {% else %}
                                <td>
                                    <form method="post" action="{% url 'complete_task' tasks.id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="is_completed" value="True">
                                        <button>Complete</button>
                                    </form>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>You have no tasks</p>
        {% endif %}
    </div>
{% endblock main %}